FROM ubuntu:22.04

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        g++ \
        gcc \
        cmake \
        gfortran \
        make \
        nano \
        liblapack-dev \
        liblapack3 \
        libopenblas-base \
        libopenblas-dev \
        r-base-dev \
        python3-dev \
        python3-venv \
        python3-pip \
        libcurl4-openssl-dev \
        libssl-dev \
        libpng-dev \
        libxml2-dev \
        r-cran-rstan \
        git \
        wget \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN python -m pip install nevergrad

RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile 
RUN Rscript -e "install.packages('remotes'); if (!library(remotes, logical.return=T)) quit(status=10)"
RUN Rscript -e "install.packages('RCurl'); if (!library(RCurl, logical.return=T)) quit(status=10)"

RUN Rscript -e "Sys.setenv('NOT_CRAN'='true'); install.packages('arrow'); if (!library(arrow, logical.return=T)) quit(status=10)"
RUN Rscript -e "install.packages('reticulate'); if (!library(reticulate, logical.return=T)) quit(status=10)"
RUN Rscript -e "install.packages('h2o', type='source', repos=(c('http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R'))); if (!library(h2o, logical.return=T)) quit(status=10)"
RUN Rscript -e "install.packages('plumber'); if (!library(plumber, logical.return=T)) quit(status=10)"
RUN Rscript -e "install.packages('png'); if (!library(png, logical.return=T)) quit(status=10)"

RUN Rscript -e "remotes::install_github('facebookexperimental/Robyn/R'); if (!library(Robyn, logical.return=T)) quit(status=10)"

RUN Rscript -e "reticulate::use_python('/usr/bin/python')"
RUN Rscript -e "reticulate::py_config()"

RUN python -m pip install matplotlib

WORKDIR /app

WGET https://raw.githubusercontent.com/arowley-ai/robyn-api/main/docker/robyn-api.r /app/robyn-api.r

EXPOSE 8000

CMD ["Rscript","-e","library(plumber); plumb('./robyn-api.r') %>% pr_run(host='0.0.0.0',port=8000)"]
